### ISSUE TITLE
Why did you choose K=11?

### ISSUE THREAD

**Issue by yaseryacoob** [CompVis/cleandift#1]
Thanks for sharing the code. As I went through the paper I am intrigued about the particular choice of K=11. Looking at Figure 11 I can see intuitively why you skipped a feature map before the Upsampling in each Decoder block, (you could have added a Feature map between #2 and #3, #5 and #6 etc). But less clear on why there is no feature map #11 or maybe #12 after the current map #10. Can you please explain?

**Comment by stefan-baumann** [comment]
Thank you for this question! Generally, near the diffusion model's output, the features are not really semantic anymore. I'm unaware of any works that found features this close to the output particularly useful. We chose to focus on aligning features that are actually commonly used (and not spend model capacity on providing more aligned feature maps that won't be used anyways). Also, aligning these additional feature maps later in the network didn't seem to be beneficial in practice.

**Comment by yaseryacoob** [comment]
Thanks for the quick response. I don't have a personal insight. But by the same arguments could you have done with just let's say 5 layers? Let's say Map 0, 3,6,9,10? 

Another question is this, am I correct inferring that your projection heads essentially "learned" the noise schedule? 

it is all intriguing and again thanks for the work and sharing the code.

**Comment by stefan-baumann** [comment]
Yes, fewer layers could have also sufficed, but would have limited the general applicability of the checkpoints we released. We also expect that aligning multiple feature maps simultaneously should give a better training signal and adapt the architecture in a more holistic manner.

Regarding your second question, yes, these projection heads learn which features occur at which timestep and align the final feature maps accordingly. The relevant background here is that, in a very simplified view, diffusion features extracted at higher noise levels contain more abstract information - effectively, we don't just get one feature map with various levels of fidelity and noise, we get 1000 different ones (this is also why it's crucial for DIFT etc to add noise to the images before extracting features! Low-noise features are just not that useful). The heads enable accessing clean versions of each one of them, and make training more well-defined, rather than effectively averaging over these 1000 slightly different feature representations.

**Comment by yaseryacoob** [comment]
Thanks for the feedback Stefan. I appreciate it and will continue exploring it. Well done.

**Comment by stefan-baumann** [comment]
Thanks! I'm always happy to talk about these things :)

I'll close the issue for now unless you still have any open questions. Please feel free to reopen it if there's anything else.
